### ISSUE TITLE
Opensourcen DT API

### ISSUE THREAD

**Issue by annejan** [minvws/nl-covid19-dienst-testen-api#78]
### Checklist
- [x] Update documents
- [x] Sanity check code / commits
- [x] Check, and if needed correct, license files
- [x] Code review by team security
- [x] Readme check by member from other team
- [x] Sig.EU code quality check
- [x] ~~- Create public repo~~
  - [x] ~~- Set-up repo sync~~
- [x] Approval PO
- [X] Approval MT
- [x] Configure repo for public use
    - [x] Branch protection

**Comment by sigio** [comment]
Publiek gezet
